#Secify version of docker compose
version: "3"

#Specify services included in our application
services:
  client:
    image: client
    build: ./frontend/
    stdin_open: true
    ports:
      - "2000:2000"
    networks:
      - mern-app

  api-server:
    image: api-server
    build: ./backend/
    ports:
      - "3000:3000"
    networks:
      - mern-app

networks:
  mern-app:
    driver: bridge
